Import('env')
myEnv = env
flags = myEnv['CCFLAGS']
parser = myEnv.Command('#/bin/src/lib/parser.tab.cpp', 'parser.ypp', 'bison -r solved $SOURCE -o $TARGET')
if (env['isShared']):
  ret = myEnv.SharedLibrary('lightgrep', Glob('*.cpp'))
else:
  ret = myEnv.Library('lightgrep', Glob('*.cpp'))
Return('ret')
