Import('env', 'boostType')
libs = ['lightgrep', 'boost_program_options' + boostType]
optSrcs = env.Glob('#/src/cmd/opt*.cpp')
testSrcs = env.Glob('*.cpp')
testSrcs.extend(optSrcs)
ret = env.Program('test', testSrcs, LIBS=libs)
Return('ret')
