Import('env', 'isWindows', 'isLinux')
libs = ['icuuc', 'icudata', 'm', 'dl']

if (isLinux):
  libs.append('pthread')
elif (isWindows):
  libs.extend(['ws2_32', 'mswsock']) # so stupid that I have to specify winsock

ret = env.Program('encodings', Glob('*.cpp'), LIBS=libs)
Return('ret')
