Import('env', 'isWindows', 'isLinux', 'boostType')
libs = ['lightgrep']
libs.extend([lib + boostType for lib in
                 ['boost_system', 'boost_thread', 'boost_program_options']])
if (isLinux):
  libs.append('pthread')
elif (isWindows):
  libs.append('ws2_32') # so stupid that I have to specify winsock
ret = env.Program('lightgrep', Glob('*.cpp'), LIBS=libs)
Return('ret')
