Import('env', 'isWindows', 'isLinux', 'isDarwin')
env = env.Clone(CXXFLAGS='')
env.Append(CCFLAGS=' -std=c99')

libs = ['lightgrep', 'icuuc', 'icudata']
if (isDarwin == False):
  libs.extend(['m', 'dl'])
if (isLinux):
  libs.append('pthread')
elif (isWindows):
  libs.extend(['ws2_32', 'mswsock']) # so stupid that I have to specify winsock

ret = env.Program('c_example', Glob('*.c'), LIBS=libs)
Return('ret')
