Import('env', 'isWindows', 'isLinux')
libs = ['lightgrep', 'icuuc', 'libstdc++']
env = env.Clone(CXXFLAGS='')
env.Append(CCFLAGS=' -std=c99')
ret = env.Program('c_example', Glob('*.c'), LIBS=libs, LINKFLAGS='-static-libgcc')
Return('ret')
